#!/bin/sh
set -efu

pys="$(py3versions -s 2> /dev/null)"

cp -a docs pytest.ini conftest.py "$AUTOPKGTEST_TMP"
cd "$AUTOPKGTEST_TMP"

for py in $pys; do
	echo "=== $py ==="
	$py -m pytest -c pytest.ini /usr/lib/python3/dist-packages/testfixtures 2>&1
	$py -m pytest docs 2>&1
done
